package com.studenthub.studentservicehub.model;

import jakarta.persistence.*;

@Entity
@Table(name = "items")
public class Item {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long itemId;

    private String name;
    private Double price;
    private Integer stockQty;// stock visibility [cite: 65]

    // --- CONSTRUCTORS ---

    // 1. Mandatory no-argument constructor for Hibernate (JPA specification requires it)
    public Item() {
    }

    // 2. Optional constructor for convenient creation (recommended)
    public Item(String name, Double price, Integer stockQty) {
        this.name = name;
        this.price = price;
        this.stockQty = stockQty;
    }

    // --- GETTERS AND SETTERS (Encapsulation) ---

    public Long getItemId() { return itemId; }
    // Setter for itemId is usually omitted or private if autogenerated

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public Double getPrice() { return price; }
    public void setPrice(Double price) { this.price = price; }

    public Integer getStockQty() { return stockQty; }
    public void setStockQty(Integer stockQty) { this.stockQty = stockQty; }

    // Method from report:
    public void updateStock(int change) {
        this.stockQty += change;
    }
}