package com.studenthub.studentservicehub.model;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.time.LocalDateTime;

// MappedSuperclass: Base class whose fields are inherited by entities, but not an entity itself
@MappedSuperclass
public abstract class Notification {

    // --- Primary Key (Identifier) ---
    @Id // <--- FIX: This provides the primary key required by all inheriting @Entity classes
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long notificationId;

    // --- Common Fields ---
    private String recipientEmail;
    private String messageBody;
    private String status;
    private LocalDateTime sentTime;

    // Report: Polymorphism to send different types of alerts through a unified interface

    // --- Constructors ---
    public Notification() {}

    // --- Getters and Setters (Encapsulation) ---

    public Long getNotificationId() { return notificationId; }
    // No setter needed for autogenerated ID

    public String getRecipientEmail() { return recipientEmail; }
    public void setRecipientEmail(String recipientEmail) { this.recipientEmail = recipientEmail; }

    public String getMessageBody() { return messageBody; }
    public void setMessageBody(String messageBody) { this.messageBody = messageBody; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getSentTime() { return sentTime; }
    public void setSentTime(LocalDateTime sentTime) { this.sentTime = sentTime; }
}