package com.studenthub.studentservicehub.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "orders") // Maps the class to the 'orders' table [cite: 238]
public class Order {

    // --- Attributes corresponding to Database Design [cite: 264-265] ---

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long orderId; // OrderID (PK)

    // Many-to-one relationship with Student [cite: 266]
    @ManyToOne
    @JoinColumn(name = "student_id") // Maps to StudentID (FK)
    private Student student;

    // Many-to-one relationship with Item [cite: 266]
    @ManyToOne
    @JoinColumn(name = "item_id") // Maps to ItemID (FK)
    private Item item;

    private Integer quantity;
    private Double totalAmount;
    private String paymentStatus;
    private String qrCode; // QRCode [cite: 265]
    private LocalDateTime orderDate = LocalDateTime.now();


    // --- Constructors ---

    // Mandatory public no-argument constructor for Hibernate (JPA requirement)
    public Order() {
    }

    // Constructor for creating a new order
    public Order(Student student, Item item, Integer quantity, Double totalAmount, String paymentStatus) {
        this.student = student;
        this.item = item;
        this.quantity = quantity;
        this.totalAmount = totalAmount;
        this.paymentStatus = paymentStatus;
        // orderDate is initialized by default
    }


    // --- Getters and Setters (Encapsulation) [cite: 132, 239] ---

    public Long getOrderId() { return orderId; }
    // Setter for orderId is usually omitted if autogenerated

    public Student getStudent() { return student; }
    public void setStudent(Student student) { this.student = student; }

    public Item getItem() { return item; }
    public void setItem(Item item) { this.item = item; }

    public Integer getQuantity() { return quantity; }
    public void setQuantity(Integer quantity) { this.quantity = quantity; }

    public Double getTotalAmount() { return totalAmount; }
    public void setTotalAmount(Double totalAmount) { this.totalAmount = totalAmount; }

    public String getPaymentStatus() { return paymentStatus; }
    public void setPaymentStatus(String paymentStatus) { this.paymentStatus = paymentStatus; }

    public String getQrCode() { return qrCode; }
    // Method from report: generateQRCode() [cite: 321] would call this setter
    public void setQrCode(String qrCode) { this.qrCode = qrCode; }

    public LocalDateTime getOrderDate() { return orderDate; }
    public void setOrderDate(LocalDateTime orderDate) { this.orderDate = orderDate; }

    // Method from report: placeOrder() [cite: 321] would use setters and repository.
    // public void placeOrder() { ... }
}
