package com.studenthub.studentservicehub.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments") // Maps the class to the 'payments' table
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId; // PaymentID (PK)

    // One-to-one relationship with Order
    @OneToOne
    @JoinColumn(name = "order_id") // Maps to OrderID (FK)
    private Order order;

    private String method;// Razorpay/UPI for digital payments [cite: 32, 66]
    private String transactionId;
    private Double amount;
    private String status;
    private LocalDateTime paymentTime = LocalDateTime.now();


    // --- Constructors ---

    // Mandatory public no-argument constructor for Hibernate (JPA requirement)
    public Payment() {
    }

    // Constructor for creating a new payment record
    public Payment(Order order, String method, String transactionId, Double amount, String status) {
        this.order = order;
        this.method = method;
        this.transactionId = transactionId;
        this.amount = amount;
        this.status = status;
        // paymentTime is initialized by default
    }


    // --- Getters and Setters (Encapsulation) ---

    public Long getPaymentId() { return paymentId; }
    // Setter for paymentId is usually omitted if autogenerated

    public Order getOrder() { return order; }
    public void setOrder(Order order) { this.order = order; }

    public String getMethod() { return method; }
    public void setMethod(String method) { this.method = method; }

    public String getTransactionId() { return transactionId; }
    public void setTransactionId(String transactionId) { this.transactionId = transactionId; }

    public Double getAmount() { return amount; }
    public void setAmount(Double amount) { this.amount = amount; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public LocalDateTime getPaymentTime() { return paymentTime; }
    public void setPaymentTime(LocalDateTime paymentTime) { this.paymentTime = paymentTime; }
}